name: Swift Matrix

on:
  workflow_call:
    inputs:
      swift_versions:
        type: string
        description: "Swift version list"
        default: ["5.8", "5.9", "5.10", "6.0", "nightly-main", "nightly-6.0"]
        required: true
      os_versions:
        type: string
        description: "OS version list"
        default: ["jammy"]
        required: true
      swift_flags:
        type: string
        description: "Swift flangs for release version"
        default: ""
      swift_nightly_flags:
        type: string
        description: "Swift flangs for nightly version"
        default: ""

jobs:
  build:
    name: Linux (${{ matrix.swift_version }} - ${{ matrix.os_version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift_version: ${{ inputs.swift_versions }}
        os_version: ${{ inputs.os_versions }}
    container: ${{ (contains(matrix.swift_version, 'nightly') && 'swiftlang/swift') || 'swift' }}:${{ matrix.swift_version }}
    steps:
      - uses: actions/checkout@v2
      - run: swift test ${{ (contains(matrix.swift_version, 'nightly') && inputs.swift_nightly_flags) || inputs.swift_flags }}
